#!/usr/bin/env python
"""Build ./samples/mixed_folder -- one folder to try the app on.

Everything here is derived from the public DICOMs bundled with pydicom
(redistributable, no PHI, no download). Run:

    .venv/bin/python scripts/make_samples.py

then press "Open folder…" in the UI and pick samples/mixed_folder.

One folder on purpose: it mixes modalities, pixel sizes and file formats, which
is what the file list and per-image geometry exist for. Every file shows
something the others do not -- no image appears twice in two formats.
"""
from __future__ import annotations
import shutil
import sys
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from PIL import Image  # noqa: E402
from pydicom.data import get_testdata_file  # noqa: E402

from media.loader import load_one  # noqa: E402  (also a smoke test of the loader)

OUT = ROOT / "samples"

# A folder that mixes modalities, sizes and file formats -- the case the file
# list and per-file geometry exist for.
MIXED = [
    ("001_ct_512.dcm", "693_UNCR.dcm", "512x512 CT, realistic resolution"),
    ("002_mr_1024.dcm", "MR2_UNCR.dcm", "1024x1024 MR"),
    ("003_mr_siemens.dcm", "MR-SIEMENS-DICOM-WithOverlays.dcm", "484x484 Siemens MR"),
    ("004_us_palette.dcm", "OBXXXX1A.dcm", "600x800 obstetric US, PALETTE COLOR"),
    ("005_cr_chest.dcm", "RG1_UNCR.dcm", "1955x1841 chest CR, MONOCHROME1 (inverted)"),
    ("006_us_grayscale.dcm", "JPGLosslessP14SV1_1s_1f_8b.dcm", "768x1024 grayscale US"),
]

# Ordinary pictures, so the PNG/JPEG path has something real in it rather than a
# synthetic gradient. Their source DICOMs are deliberately not copied in as well:
# the folder should not hold the same image twice.
AS_PICTURES = [
    ("007_ct_chest.png", "CT_small.dcm", "PNG"),
    ("008_us_colour.jpg", "US1_J2KR.dcm", "JPEG"),
]


def _fetch(name: str) -> Path | None:
    """Locate a DICOM file bundled with pydicom.

    Args:
        name: The fixture's filename, e.g. ``CT_small.dcm``.

    Returns:
        Its path, or None if this pydicom build does not ship it -- the sample
        is then skipped rather than failing the run.
    """
    path = get_testdata_file(name)
    return Path(path) if path else None


def write_picture(src: Path, dest: Path, kind: str) -> None:
    """Render a DICOM frame to a normal image file, through the app's own reader.

    Going through the loader means the pictures show the same pixels the app
    would display, and doubles as a smoke test of the reader.

    Args:
        src: The source DICOM.
        dest: Where to write; the extension should match ``kind``.
        kind: ``"PNG"`` or ``"JPEG"``.
    """
    source = load_one(src.name, src.read_bytes())
    arr = source.frame_uint8(0)
    im = Image.fromarray(arr)
    if kind == "JPEG":
        im.convert("RGB").save(dest, quality=92)
    else:
        im.save(dest)


def main() -> int:
    """Rebuild ``samples/`` from scratch and print what was written.

    Returns:
        A process exit code; always 0. Fixtures this pydicom build does not have
        are reported and skipped.
    """
    if OUT.exists():
        shutil.rmtree(OUT)
    mixed = OUT / "mixed_folder"
    mixed.mkdir(parents=True)
    print(f"writing to {OUT}\n")
    print("samples/mixed_folder  -- press \"Open folder…\" and pick this one")

    rows: list[tuple[str, Path, str]] = []
    for dest_name, src_name, why in MIXED:
        src = _fetch(src_name)
        if not src:
            print(f"  SKIP {src_name} (not available)")
            continue
        shutil.copy(src, mixed / dest_name)
        rows.append((dest_name, mixed / dest_name, why))

    for dest_name, src_name, kind in AS_PICTURES:
        src = _fetch(src_name)
        if not src:
            continue
        write_picture(src, mixed / dest_name, kind)
        rows.append((dest_name, mixed / dest_name, f"{kind} rendered from {src_name}"))

    for name, path, why in rows:
        print(f"  {name:24} {path.stat().st_size / 1024:7.0f} KB  {why}")

    (OUT / "README.md").write_text(
        "# sample images\n\n"
        "Generated by `scripts/make_samples.py` from the public DICOMs bundled\n"
        "with pydicom. No PHI, nothing downloaded.\n\n"
        "`mixed_folder/` — CT, MR and ultrasound at sizes from 128×128 to\n"
        "1955×1841, in DICOM, PNG and JPEG. Each image appears once.\n"
        "Load it with **Open folder…**.\n"
    )

    total = sum(f.stat().st_size for f in OUT.rglob("*") if f.is_file())
    print(f"\nready: {sum(1 for f in OUT.rglob('*') if f.is_file())} files, {total/1024/1024:.1f} MB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
